steps:
# 1. Dockerイメージをビルドするステップ
- name: 'gcr.io/cloud-builders/docker'
  args:
    - 'build'
    - '--target=production'
    - '-t'
    - 'asia-northeast1-docker.pkg.dev/$PROJECT_ID/k-back-repo/k-back:latest'
    - '.' 

# 2. ビルドしたイメージをArtifact Registryにプッシュするステップ
- name: 'gcr.io/cloud-builders/docker'
  args:
    - 'push'
    - 'asia-northeast1-docker.pkg.dev/$PROJECT_ID/k-back-repo/k-back:latest'

# 3. プッシュしたイメージを使ってCloud Runにデプロイするステップ
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: gcloud
  args:
    - 'run'
    - 'deploy'
    - 'k-back'
    - '--image'
    - 'asia-northeast1-docker.pkg.dev/$PROJECT_ID/k-back-repo/k-back:latest'
    - '--region'
    - 'asia-northeast1'
    - '--platform'
    - 'managed'
    - '--allow-unauthenticated'
    - '--update-env-vars'
    - '^##^DATABASE_URL=${_PROD_DATABASE_URL}##SECRET_KEY=${_PROD_SECRET_KEY}##MAIL_USERNAME=${_AWS_ACCESS_KEY_ID}##MAIL_PASSWORD=${_AWS_SECRET_ACCESS_KEY}##MAIL_FROM=${_SENDER_EMAIL}##MAIL_SERVER=${_MAIL_SERVER}##MAIL_PORT=${_MAIL_PORT}##FRONTEND_URL=${_FRONTEND_URL}##AWS_REGION=${_AWS_REGION}##MAIL_STARTTLS=True##MAIL_SSL_TLS=False##MAIL_DEBUG=False'

# ビルドしたイメージを保存する
images:
  - 'asia-northeast1-docker.pkg.dev/$PROJECT_ID/k-back-repo/k-back:latest'