"""Add ondelete=CASCADE to foreign keys

Revision ID: 19ae7717a905
Revises: dd8baa1ce679
Create Date: 2025-08-23 07:07:50.953175

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '19ae7717a905'
down_revision: Union[str, None] = 'dd8baa1ce679'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    # --- offices table ---
    # Drop the old FK constraints
    op.drop_constraint('offices_created_by_fkey', 'offices', type_='foreignkey')
    op.drop_constraint('offices_last_modified_by_fkey', 'offices', type_='foreignkey')
    # Create new FK constraints with ON DELETE CASCADE
    op.create_foreign_key(
        'offices_created_by_fkey',
        'offices',
        'staffs',
        ['created_by'],
        ['id'],
        ondelete='CASCADE'
    )
    op.create_foreign_key(
        'offices_last_modified_by_fkey',
        'offices',
        'staffs',
        ['last_modified_by'],
        ['id'],
        ondelete='CASCADE'
    )

    # --- office_staffs table ---
    # Drop the old FK constraints
    op.drop_constraint('office_staffs_office_id_fkey', 'office_staffs', type_='foreignkey')
    op.drop_constraint('office_staffs_staff_id_fkey', 'office_staffs', type_='foreignkey')
    # Create new FK constraints with ON DELETE CASCADE
    op.create_foreign_key(
        'office_staffs_office_id_fkey',
        'office_staffs',
        'offices',
        ['office_id'],
        ['id'],
        ondelete='CASCADE'
    )
    op.create_foreign_key(
        'office_staffs_staff_id_fkey',
        'office_staffs',
        'staffs',
        ['staff_id'],
        ['id'],
        ondelete='CASCADE'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    # --- office_staffs table ---
    # Drop the CASCADE FK constraints
    op.drop_constraint('office_staffs_office_id_fkey', 'office_staffs', type_='foreignkey')
    op.drop_constraint('office_staffs_staff_id_fkey', 'office_staffs', type_='foreignkey')
    # Recreate the original FK constraints
    op.create_foreign_key('office_staffs_office_id_fkey', 'office_staffs', 'offices', ['office_id'], ['id'])
    op.create_foreign_key('office_staffs_staff_id_fkey', 'office_staffs', 'staffs', ['staff_id'], ['id'])

    # --- offices table ---
    # Drop the CASCADE FK constraints
    op.drop_constraint('offices_created_by_fkey', 'offices', type_='foreignkey')
    op.drop_constraint('offices_last_modified_by_fkey', 'offices', type_='foreignkey')
    # Recreate the original FK constraints
    op.create_foreign_key('offices_created_by_fkey', 'offices', 'staffs', ['created_by'], ['id'])
    op.create_foreign_key('offices_last_modified_by_fkey', 'offices', 'staffs', ['last_modified_by'], ['id'])
    # ### end Alembic commands ###