"""Add

Revision ID: 5b4c05509ed2
Revises: a04c2a87f41d
Create Date: 2025-08-26 06:25:20.645643

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.sql import expression

# revision identifiers, used by Alembic.
revision: str = '5b4c05509ed2'
down_revision: Union[str, None] = 'a04c2a87f41d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('staffs', sa.Column('is_email_verified', sa.Boolean(), nullable=False, server_default=expression.false()))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('staffs', 'is_email_verified')
    # ### end Alembic commands ###
