"""dashboard

Revision ID: 7fa9fdd58c84
Revises: e55891321878
Create Date: 2025-09-11 01:14:28.436941

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7fa9fdd58c84'
down_revision: Union[str, None] = 'e55891321878'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('welfare_recipients',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('first_name', sa.String(length=255), nullable=False),
    sa.Column('last_name', sa.String(length=255), nullable=False),
    sa.Column('furigana', sa.String(length=255), nullable=False),
    sa.Column('birth_day', sa.Date(), nullable=False),
    sa.Column('gender', sa.Enum('male', 'female', 'other', name='gendertype'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('office_welfare_recipients',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('welfare_recipient_id', sa.UUID(), nullable=False),
    sa.Column('office_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['office_id'], ['offices.id'], ),
    sa.ForeignKeyConstraint(['welfare_recipient_id'], ['welfare_recipients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('support_plan_cycles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('welfare_recipient_id', sa.UUID(), nullable=False),
    sa.Column('plan_cycle_start_date', sa.Date(), nullable=False),
    sa.Column('final_plan_signed_date', sa.Date(), nullable=True),
    sa.Column('next_renewal_deadline', sa.Date(), nullable=True),
    sa.Column('is_latest_cycle', sa.Boolean(), nullable=False),
    sa.Column('google_calendar_id', sa.Text(), nullable=True),
    sa.Column('google_event_id', sa.Text(), nullable=True),
    sa.Column('google_event_url', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['welfare_recipient_id'], ['welfare_recipients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('support_plan_statuses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('plan_cycle_id', sa.Integer(), nullable=False),
    sa.Column('step_type', sa.Enum('assessment', 'draft_plan', 'staff_meeting', 'final_plan_signed', 'monitoring', name='supportplanstep'), nullable=False),
    sa.Column('completed', sa.Boolean(), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_by', sa.UUID(), nullable=True),
    sa.Column('monitoring_deadline', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['completed_by'], ['staffs.id'], ),
    sa.ForeignKeyConstraint(['plan_cycle_id'], ['support_plan_cycles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('plan_deliverables',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('plan_cycle_id', sa.Integer(), nullable=False),
    sa.Column('deliverable_type', sa.Enum('assessment_sheet', 'draft_plan_pdf', 'staff_meeting_minutes', 'final_plan_signed_pdf', 'monitoring_report_pdf', name='deliverabletype'), nullable=False),
    sa.Column('file_path', sa.Text(), nullable=False),
    sa.Column('original_filename', sa.Text(), nullable=False),
    sa.Column('uploaded_by', sa.UUID(), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['plan_cycle_id'], ['support_plan_cycles.id'], ),
    sa.ForeignKeyConstraint(['uploaded_by'], ['staffs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('plan_deliverables')
    op.drop_table('support_plan_statuses')
    op.drop_table('support_plan_cycles')
    op.drop_table('office_welfare_recipients')
    op.drop_table('welfare_recipients')
    sa.Enum(name='supportplanstep').drop(op.get_bind(), checkfirst=False)
    sa.Enum(name='gendertype').drop(op.get_bind(), checkfirst=False)
    sa.Enum(name='deliverabletype').drop(op.get_bind(), checkfirst=False)
    # ### end Alembic commands ###