"""Update enum definitions

Revision ID: a04c2a87f41d
Revises: 19ae7717a905
Create Date: 2025-08-26 02:44:17.429872

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a04c2a87f41d'
down_revision: Union[str, None] = '19ae7717a905'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # StaffRoleの更新
    op.execute("ALTER TYPE staffrole RENAME TO staffrole_old")
    op.execute("CREATE TYPE staffrole AS ENUM('employee', 'manager', 'owner')")
    op.execute("""
        ALTER TABLE staffs
        ALTER COLUMN role
        TYPE staffrole
        USING
          CASE role::text
            WHEN 'service_administrator' THEN 'owner'::staffrole
            WHEN 'general_staff' THEN 'employee'::staffrole
            ELSE 'employee'::staffrole
          END
    """)
    op.execute("DROP TYPE staffrole_old")

    # OfficeTypeの更新
    op.execute("ALTER TYPE officetype RENAME TO officetype_old")
    op.execute("CREATE TYPE officetype AS ENUM('transition_to_employment', 'type_B_office', 'type_A_office')")
    op.execute("""
        ALTER TABLE offices
        ALTER COLUMN type
        TYPE officetype
        USING
          CASE type::text
            WHEN 'main_office' THEN 'transition_to_employment'::officetype
            WHEN 'satellite_office' THEN 'type_B_office'::officetype
            ELSE 'transition_to_employment'::officetype
          END
    """)
    op.execute("DROP TYPE officetype_old")

    # BillingStatusの更新
    op.execute("ALTER TYPE billingstatus RENAME TO billingstatus_old")
    op.execute("CREATE TYPE billingstatus AS ENUM('free', 'active', 'past_due', 'canceled')")
    op.execute("""
        ALTER TABLE offices
        ALTER COLUMN billing_status
        TYPE billingstatus
        USING
          CASE billing_status::text
            WHEN 'paid' THEN 'active'::billingstatus
            WHEN 'delinquent' THEN 'past_due'::billingstatus
            WHEN 'free' THEN 'free'::billingstatus
            ELSE 'free'::billingstatus
          END
    """)
    op.execute("DROP TYPE billingstatus_old")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # StaffRoleのダウングレード
    op.execute("ALTER TYPE staffrole RENAME TO staffrole_new")
    op.execute("CREATE TYPE staffrole AS ENUM('service_administrator', 'general_staff')")
    op.execute("""
        ALTER TABLE staffs
        ALTER COLUMN role
        TYPE staffrole
        USING
          CASE role::text
            WHEN 'owner' THEN 'service_administrator'::staffrole
            WHEN 'manager' THEN 'general_staff'::staffrole
            WHEN 'employee' THEN 'general_staff'::staffrole
            ELSE 'general_staff'::staffrole
          END
    """)
    op.execute("DROP TYPE staffrole_new")

    # OfficeTypeのダウングレード
    op.execute("ALTER TYPE officetype RENAME TO officetype_new")
    op.execute("CREATE TYPE officetype AS ENUM('main_office', 'satellite_office')")
    op.execute("""
        ALTER TABLE offices
        ALTER COLUMN type
        TYPE officetype
        USING
          CASE type::text
            WHEN 'transition_to_employment' THEN 'main_office'::officetype
            WHEN 'type_B_office' THEN 'satellite_office'::officetype
            WHEN 'type_A_office' THEN 'satellite_office'::officetype
            ELSE 'main_office'::officetype
          END
    """)
    op.execute("DROP TYPE officetype_new")

    # BillingStatusのダウングレード
    op.execute("ALTER TYPE billingstatus RENAME TO billingstatus_new")
    op.execute("CREATE TYPE billingstatus AS ENUM('free', 'paid', 'delinquent')")
    op.execute("""
        ALTER TABLE offices
        ALTER COLUMN billing_status
        TYPE billingstatus
        USING
          CASE billing_status::text
            WHEN 'active' THEN 'paid'::billingstatus
            WHEN 'past_due' THEN 'delinquent'::billingstatus
            WHEN 'canceled' THEN 'free'::billingstatus
            WHEN 'free' THEN 'free'::billingstatus
            ELSE 'free'::billingstatus
          END
    """)
    op.execute("DROP TYPE billingstatus_new")
    # ### end Alembic commands ###
